import type { PotholeReport, Zone } from '@/lib/types';
import { subDays } from 'date-fns';

export const zones: Zone[] = [
  { name: 'Teynampet', center: { lat: 13.047, lng: 80.252 }, potholes: { reported: 12, filled: 8 } },
  { name: 'Adyar', center: { lat: 13.004, lng: 80.254 }, potholes: { reported: 8, filled: 5 } },
  { name: 'Anna Nagar', center: { lat: 13.085, lng: 80.210 }, potholes: { reported: 15, filled: 10 } },
  { name: 'Tondiarpet', center: { lat: 13.125, lng: 80.297 }, potholes: { reported: 5, filled: 2 } },
  { name: 'Royapuram', center: { lat: 13.116, lng: 80.299 }, potholes: { reported: 7, filled: 6 } },
  { name: 'Thiru-Vi-Ka Nagar', center: { lat: 13.115, lng: 80.239 }, potholes: { reported: 9, filled: 4 } },
  { name: 'Ambattur', center: { lat: 13.114, lng: 80.155 }, potholes: { reported: 18, filled: 11 } },
  { name: 'Valasaravakkam', center: { lat: 13.050, lng: 80.174 }, potholes: { reported: 6, filled: 3 } },
  { name: 'Alandur', center: { lat: 12.997, lng: 80.201 }, potholes: { reported: 11, filled: 9 } },
  { name: 'Perungudi', center: { lat: 12.964, lng: 80.245 }, potholes: { reported: 14, filled: 7 } },
];

export const reports: PotholeReport[] = [
  {
    id: 'rep-001',
    description: 'Deep pothole near the bus stop, causing traffic slowdown.',
    location: { lat: 13.0475, lng: 80.2525 },
    address: '123, Anna Salai, Teynampet',
    zone: 'Teynampet',
    status: 'In Progress',
    severity: 'High',
    reportedAt: subDays(new Date(), 2),
    imageUrl: 'https://picsum.photos/400/300?random=1',
  },
  {
    id: 'rep-002',
    description: 'Multiple small potholes on the side of the road.',
    location: { lat: 13.0042, lng: 80.2548 },
    address: '45, Besant Nagar Beach Road, Adyar',
    zone: 'Adyar',
    status: 'Completed',
    severity: 'Medium',
    reportedAt: subDays(new Date(), 10),
    filledAt: subDays(new Date(), 3),
    imageUrl: 'https://picsum.photos/400/300?random=2',
  },
  {
    id: 'rep-003',
    description: 'Large pothole at the intersection, very dangerous at night.',
    location: { lat: 13.0851, lng: 80.2105 },
    address: '7, 2nd Avenue, Anna Nagar',
    zone: 'Anna Nagar',
    status: 'Reported',
    severity: 'High',
    reportedAt: subDays(new Date(), 1),
    imageUrl: 'https://picsum.photos/400/300?random=3',
  },
  {
    id: 'rep-004',
    description: 'Road surface is cracking, multiple small issues.',
    location: { lat: 13.1255, lng: 80.2973 },
    address: '110, Ennore High Road, Tondiarpet',
    zone: 'Tondiarpet',
    status: 'Completed',
    severity: 'Low',
    reportedAt: subDays(new Date(), 30),
    filledAt: subDays(new Date(), 15),
    imageUrl: 'https://picsum.photos/400/300?random=4',
  },
  {
    id: 'rep-005',
    description: 'Pothole has been here for weeks, getting bigger.',
    location: { lat: 13.1162, lng: 80.2991 },
    address: '21, Rajaji Salai, Royapuram',
    zone: 'Royapuram',
    status: 'In Progress',
    severity: 'Medium',
    reportedAt: subDays(new Date(), 18),
    imageUrl: 'https://picsum.photos/400/300?random=5',
  },
  {
    id: 'rep-006',
    description: 'Minor pothole, not a major issue but should be looked at.',
    location: { lat: 13.048, lng: 80.253 },
    address: '24, Cenotaph Road, Teynampet',
    zone: 'Teynampet',
    status: 'Reported',
    severity: 'Low',
    reportedAt: subDays(new Date(), 5),
    imageUrl: 'https://picsum.photos/400/300?random=6',
  },
];
