import type { PotholeReport, Zone } from '@/lib/types';

export const zones: Zone[] = [
  { name: 'Teynampet', center: { lat: 13.047, lng: 80.252 }, potholes: { reported: 12, filled: 5 } },
  { name: 'Adyar', center: { lat: 13.004, lng: 80.254 }, potholes: { reported: 8, filled: 6 } },
  { name: 'Anna Nagar', center: { lat: 13.085, lng: 80.210 }, potholes: { reported: 15, filled: 10 } },
  { name: 'Tondiarpet', center: { lat: 13.125, lng: 80.297 }, potholes: { reported: 20, filled: 8 } },
  { name: 'Royapuram', center: { lat: 13.116, lng: 80.299 }, potholes: { reported: 18, filled: 15 } },
  { name: 'Thiru-Vi-Ka Nagar', center: { lat: 13.115, lng: 80.239 }, potholes: { reported: 9, filled: 3 } },
  { name: 'Ambattur', center: { lat: 13.114, lng: 80.155 }, potholes: { reported: 25, filled: 12 } },
  { name: 'Valasaravakkam', center: { lat: 13.050, lng: 80.174 }, potholes: { reported: 7, filled: 7 } },
  { name: 'Alandur', center: { lat: 12.997, lng: 80.201 }, potholes: { reported: 11, filled: 9 } },
  { name: 'Perungudi', center: { lat: 12.964, lng: 80.245 }, potholes: { reported: 14, filled: 6 } },
];

export const reports: PotholeReport[] = [
  {
    id: 'PH001',
    description: 'Deep pothole near the bus stop, causing traffic slowdown. It has been there for a week and is getting bigger.',
    location: { lat: 13.048, lng: 80.255 },
    address: '123, Anna Salai, Teynampet',
    zone: 'Teynampet',
    status: 'Reported',
    severity: 'High',
    reportedAt: new Date('2024-07-20T09:00:00Z'),
    imageUrl: 'https://picsum.photos/600/400',
    userId: 'user1',
  },
  {
    id: 'PH002',
    description: 'Multiple small potholes on the side street.',
    location: { lat: 13.005, lng: 80.259 },
    address: '45, Besant Nagar Beach Rd, Adyar',
    zone: 'Adyar',
    status: 'Completed',
    severity: 'Low',
    reportedAt: new Date('2024-07-18T14:30:00Z'),
    imageUrl: 'https://picsum.photos/600/401',
    userId: 'user2',
  },
  {
    id: 'PH003',
    description: 'A large section of the road is damaged. Water is stagnating in the pothole. Very dangerous for two-wheelers at night.',
    location: { lat: 13.088, lng: 80.212 },
    address: '2nd Avenue, Anna Nagar',
    zone: 'Anna Nagar',
    status: 'In Progress',
    severity: 'High',
    reportedAt: new Date('2024-07-21T11:00:00Z'),
    userId: 'user1',
  },
  {
    id: 'PH004',
    description: 'Pothole is moderately deep, but located at a busy intersection.',
    location: { lat: 13.126, lng: 80.295 },
    address: 'S.N. Chetty Street, Tondiarpet',
    zone: 'Tondiarpet',
    status: 'Reported',
    severity: 'Medium',
    reportedAt: new Date('2024-07-22T08:20:00Z'),
    imageUrl: 'https://picsum.photos/600/402',
    userId: 'user3',
  },
  {
    id: 'PH005',
    description: 'Road surface is uneven, but not a deep hole yet.',
    location: { lat: 12.998, lng: 80.200 },
    address: 'GST Road, Alandur',
    zone: 'Alandur',
    status: 'Completed',
    severity: 'Low',
    reportedAt: new Date('2024-07-15T18:00:00Z'),
    userId: 'user2',
  },
  {
    id: 'PH006',
    description: 'Repair work started but left incomplete, creating a hazard.',
    location: { lat: 13.115, lng: 80.158 },
    address: 'MTH Road, Ambattur',
    zone: 'Ambattur',
    status: 'In Progress',
    severity: 'Medium',
    reportedAt: new Date('2024-07-19T16:45:00Z'),
    imageUrl: 'https://picsum.photos/600/403',
    userId: 'user4',
  },
];
